-- GENERATED by tools/dev/gen-seed.ts from shared/presets.json. Do not edit.
-- Idempotent: applied after migrations on every run.

insert into public.palettes (id, name, colors) values
  ('default', 'Default (B&W)', '[{"name":"black","color":"#000000","deviceColor":"#000000"},{"name":"white","color":"#e6e6e6","deviceColor":"#ffffff"}]'::jsonb),
  ('spectra6', 'Spectra 6', '[{"name":"black","color":"#29222D","deviceColor":"#000000"},{"name":"white","color":"#C5CDCB","deviceColor":"#ffffff"},{"name":"blue","color":"#224D98","deviceColor":"#0000ff"},{"name":"green","color":"#486F5B","deviceColor":"#00ff00"},{"name":"red","color":"#76231F","deviceColor":"#ff0000"},{"name":"yellow","color":"#D5BD14","deviceColor":"#ffff00"}]'::jsonb),
  ('gallery', 'Gallery / AcEP 7c', '[{"name":"black","color":"#191E21","deviceColor":"#000000"},{"name":"white","color":"#F1F1F1","deviceColor":"#ffffff"},{"name":"blue","color":"#31318F","deviceColor":"#0000ff"},{"name":"green","color":"#53A428","deviceColor":"#00ff00"},{"name":"red","color":"#D20E13","deviceColor":"#ff0000"},{"name":"orange","color":"#B85E1C","deviceColor":"#ff8000"},{"name":"yellow","color":"#F3CF11","deviceColor":"#ffff00"}]'::jsonb)
on conflict (id) do update set name = excluded.name, colors = excluded.colors;

insert into public.device_models (id, name, width, height, palette_id) values
  ('reterminal-e1002', 'reTerminal E1002 7.3"', 800, 480, 'spectra6')
on conflict (id) do update set
  name = excluded.name, width = excluded.width, height = excluded.height, palette_id = excluded.palette_id;
