// Copies the frame backend into the app's assets, for the setup wizard and frame
// updates (PLAN.md §6.2–6.3): the migrations, seed.sql, the Edge Function sources and
// the model list, the Google/Apple sign-in settings, plus manifest.json saying what's
// where (Flutter can't list assets).
//   deno run --allow-read --allow-write tools/dev/bundle-backend.ts [--check]
//
// Run it after changing anything in backend/supabase/ or shared/presets.json (after
// gen-seed.ts). --check exits 1 if app/assets/backend is out of date (the app's tests
// check the same).

import { FUNCTIONS } from "./deploy-functions.ts";
import { authProviders } from "./lib.ts";
import { loadPresets } from "./presets.ts";

const root = new URL("../../", import.meta.url);
const src = new URL("backend/supabase/", root);
const out = new URL("app/assets/backend/", root);

async function list(dir: URL, re: RegExp): Promise<string[]> {
  const names: string[] = [];
  for await (const e of Deno.readDir(dir)) if (e.isFile && re.test(e.name)) names.push(e.name);
  return names.sort();
}

const files = new Map<string, string>(); // asset path → contents

const migrations = (await list(new URL("migrations/", src), /^\d+_.+\.sql$/)).map((name) => ({
  version: Number(name.split("_")[0]),
  file: `migrations/${name}`,
}));
for (const m of migrations) files.set(m.file, await Deno.readTextFile(new URL(m.file, src)));
files.set("seed.sql", await Deno.readTextFile(new URL("seed.sql", src)));

const functions: Record<string, string[]> = {};
for (const dir of [...FUNCTIONS, "_shared"]) {
  const paths = (await list(new URL(`functions/${dir}/`, src), /\.ts$/)).map((n) => `${dir}/${n}`);
  for (const p of paths) files.set(`functions/${p}`, await Deno.readTextFile(new URL(`functions/${p}`, src)));
  functions[dir] = paths;
}

const { models } = await loadPresets();
files.set("models.json", JSON.stringify(models.map(({ id, name, width, height }) => ({ id, name, width, height })), null, 2) + "\n");
// What a frame runs: when it differs from a frame's (same schema version), the app
// offers "Update" (the wizard writes it to private.config after deploying functions).
const sources = [...files].filter(([p]) => p !== "models.json").sort(([a], [b]) => a.localeCompare(b));
const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(sources.map(([p, c]) => `${p}\0${c}`).join("\0")));
const fingerprint = Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join("").slice(0, 16);

// The same auth config provision.ts gives a project (from shared/oauth-clients.json).
files.set("auth.json", JSON.stringify(await authProviders(), null, 2) + "\n");
files.set(
  "manifest.json",
  JSON.stringify({ about: "GENERATED by tools/dev/bundle-backend.ts. Do not edit.", fingerprint, migrations, functions }, null, 2) + "\n",
);

async function existing(): Promise<Map<string, string>> {
  const found = new Map<string, string>();
  async function walk(dir: URL, prefix: string) {
    try {
      for await (const e of Deno.readDir(dir)) {
        if (e.isDirectory) await walk(new URL(`${e.name}/`, dir), `${prefix}${e.name}/`);
        else found.set(`${prefix}${e.name}`, await Deno.readTextFile(new URL(e.name, dir)));
      }
    } catch (e) {
      if (!(e instanceof Deno.errors.NotFound)) throw e;
    }
  }
  await walk(out, "");
  return found;
}

const before = await existing();
const stale = [...files].filter(([p, c]) => before.get(p) !== c).map(([p]) => p);
const extra = [...before.keys()].filter((p) => !files.has(p));

if (Deno.args.includes("--check")) {
  if (stale.length || extra.length) {
    console.error(`app/assets/backend is out of date (${[...stale, ...extra].join(", ")}). Run tools/dev/bundle-backend.ts.`);
    Deno.exit(1);
  }
  console.log("app/assets/backend is up to date.");
  Deno.exit(0);
}

for (const p of extra) await Deno.remove(new URL(p, out));
for (const [p, contents] of files) {
  const url = new URL(p, out);
  await Deno.mkdir(new URL(".", url), { recursive: true });
  await Deno.writeTextFile(url, contents);
}
console.log(`app/assets/backend: ${migrations.length} migrations, seed, ${Object.values(functions).flat().length} function files, ${models.length} models`);
