// Generates backend/supabase/seed.sql from shared/presets.json.
//   deno run --allow-read --allow-write tools/dev/gen-seed.ts
//
// seed.sql is an idempotent upsert of palettes and device models. The migration runner
// (and the app's wizard) apply it after migrations on every run, so editing presets
// needs no new migration. Models are never deleted: frames may reference them.
// Afterwards run bundle-backend.ts, so the app gets the new seed and model list.

import { loadPresets } from "./presets.ts";

const root = new URL("../../", import.meta.url);
const lit = (s: string) => `'${s.replaceAll("'", "''")}'`;

const { palettes, models } = await loadPresets();

const sql = `-- GENERATED by tools/dev/gen-seed.ts from shared/presets.json. Do not edit.
-- Idempotent: applied after migrations on every run.

insert into public.palettes (id, name, colors) values
${palettes.map((p) => `  (${lit(p.id)}, ${lit(p.name)}, ${lit(JSON.stringify(p.colors))}::jsonb)`).join(",\n")}
on conflict (id) do update set name = excluded.name, colors = excluded.colors;

insert into public.device_models (id, name, width, height, palette_id) values
${models.map((m) => `  (${lit(m.id)}, ${lit(m.name)}, ${m.width}, ${m.height}, ${lit(m.palette)})`).join(",\n")}
on conflict (id) do update set
  name = excluded.name, width = excluded.width, height = excluded.height, palette_id = excluded.palette_id;
`;

await Deno.writeTextFile(new URL("backend/supabase/seed.sql", root), sql);
console.log(`seed.sql: ${palettes.length} palettes, ${models.length} models (${models.map((m) => m.id).join(", ")})`);
