// Generates backend/supabase/seed.sql from shared/presets.json.
//   deno run --allow-read --allow-write tools/dev/gen-seed.ts
//
// seed.sql is an idempotent upsert of palettes and device models. The migration runner
// (and the app's wizard) apply it after migrations on every run, so editing presets
// needs no new migration. Models are never deleted: frames may reference them.

const root = new URL("../../", import.meta.url);

// Preset ids come from ink-frame-lab and aren't valid model ids (spaces, dots,
// capitals). Ids that firmware builds depend on are pinned here; the rest are slugged.
const MODEL_ID_OVERRIDES: Record<string, string> = {
  "reTerminal E1002 7.3": "reterminal-e1002",
};

type Presets = {
  devices: { id: string; name: string; resolution: { w: number; h: number }; palette: string }[];
  palettes: { id: string; name: string; colors: { name: string; color: string; deviceColor: string }[] }[];
};

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const lit = (s: string) => `'${s.replaceAll("'", "''")}'`;

const presets: Presets = JSON.parse(await Deno.readTextFile(new URL("shared/presets.json", root)));

const palettes = presets.palettes.map((p) =>
  `  (${lit(p.id)}, ${lit(p.name)}, ${lit(JSON.stringify(p.colors))}::jsonb)`
);

const seen = new Set<string>();
const models = presets.devices.map((d) => {
  const id = MODEL_ID_OVERRIDES[d.id] ?? slug(d.id);
  if (!/^[a-z0-9][a-z0-9-]{1,63}$/.test(id)) throw new Error(`bad model id ${id} (from ${d.id})`);
  if (seen.has(id)) throw new Error(`duplicate model id ${id}`);
  seen.add(id);
  return `  (${lit(id)}, ${lit(d.name)}, ${d.resolution.w}, ${d.resolution.h}, ${lit(d.palette)})`;
});

const sql = `-- GENERATED by tools/dev/gen-seed.ts from shared/presets.json. Do not edit.
-- Idempotent: applied after migrations on every run.

insert into public.palettes (id, name, colors) values
${palettes.join(",\n")}
on conflict (id) do update set name = excluded.name, colors = excluded.colors;

insert into public.device_models (id, name, width, height, palette_id) values
${models.join(",\n")}
on conflict (id) do update set
  name = excluded.name, width = excluded.width, height = excluded.height, palette_id = excluded.palette_id;
`;

await Deno.writeTextFile(new URL("backend/supabase/seed.sql", root), sql);
console.log(`seed.sql: ${palettes.length} palettes, ${models.length} models (${[...seen].join(", ")})`);
