// Generates backend/supabase/functions/_shared/tz.ts: IANA timezone → POSIX TZ string,
// used by device-api to give frames a `tz_posix` for setenv("TZ") (PLAN.md §7.3).
// Also app/lib/data/timezones.dart: the zones the app's Settings offers (one per
// place, from zone.tab, so old aliases don't appear twice), plus UTC.
//   deno run --allow-read --allow-write tools/dev/gen-tz.ts [/usr/share/zoneinfo]
//
// Every TZif v2+ file ends with "\n<POSIX TZ string>\n", so the table is read straight
// from a compiled zoneinfo tree. Aliases (e.g. Asia/Calcutta) are included because
// that's what some devices report.

const zoneinfo = Deno.args[0] ?? "/usr/share/zoneinfo";
const SKIP_DIRS = new Set(["posix", "right", "SystemV"]);
const SKIP_FILES = new Set(["Factory", "localtime", "posixrules"]);

const table: Record<string, string> = {};

async function walk(dir: string, prefix: string) {
  for await (const e of Deno.readDir(dir)) {
    const name = prefix ? `${prefix}/${e.name}` : e.name;
    if (e.isDirectory) {
      if (!SKIP_DIRS.has(e.name)) await walk(`${dir}/${e.name}`, name);
      continue;
    }
    if (!e.isFile || SKIP_FILES.has(e.name) || e.name.includes(".") || e.name.startsWith("+")) continue;
    const bytes = await Deno.readFile(`${dir}/${e.name}`);
    if (new TextDecoder().decode(bytes.subarray(0, 4)) !== "TZif" || bytes[4] < 0x32) continue; // v2+
    const end = bytes.length - 1;
    if (bytes[end] !== 0x0a) continue;
    const start = bytes.lastIndexOf(0x0a, end - 1);
    const posix = new TextDecoder().decode(bytes.subarray(start + 1, end));
    if (posix) table[name] = posix;
  }
}

await walk(zoneinfo, "");
let version = "unknown";
try {
  version = (await Deno.readTextFile(`${zoneinfo}/+VERSION`)).trim();
} catch { /* not every tree has it */ }

const keys = Object.keys(table).sort();
const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(table[k])},`).join("\n");
const out = `// GENERATED by tools/dev/gen-tz.ts from tzdata ${version}. Do not edit.
// IANA timezone name → POSIX TZ string.

export const TZDATA_VERSION = ${JSON.stringify(version)};

export const TZ_POSIX: Record<string, string> = {
${body}
};
`;
await Deno.writeTextFile(new URL("../../backend/supabase/functions/_shared/tz.ts", import.meta.url), out);
console.log(`tz.ts: ${keys.length} zones from tzdata ${version}`);

// The app's list: zone.tab's zones that the table has, plus UTC.
const offered = new Set<string>(["UTC"]);
for (const line of (await Deno.readTextFile(`${zoneinfo}/zone.tab`)).split("\n")) {
  if (!line || line.startsWith("#")) continue;
  const zone = line.split("\t")[2];
  if (zone && table[zone]) offered.add(zone);
}
const zones = [...offered].sort();
const dart = `// GENERATED by tools/dev/gen-tz.ts from tzdata ${version}. Do not edit.
// The time zones Settings offers; every one is in device-api's table.

const timeZones = <String>[
${zones.map((z) => `  '${z}',`).join("\n")}
];
`;
await Deno.writeTextFile(new URL("../../app/lib/data/timezones.dart", import.meta.url), dart);
console.log(`timezones.dart: ${zones.length} zones`);
